# Developer: pendatkill
# Module: ai_detector.detector
# Description: Heuristic-based local detection of AI-generated text and images, no API calls

import os
import re
import math
from typing import Optional

try:
    from PIL import Image
    from PIL.ExifTags import TAGS
    PILLOW_AVAILABLE = True
except ImportError:
    PILLOW_AVAILABLE = False


# -----------------------------------------------------------------------
# Known AI image generator software strings (case-insensitive substrings)
# -----------------------------------------------------------------------
_AI_SOFTWARE_SIGNATURES = [
    "midjourney",
    "stable diffusion",
    "stablediffusion",
    "dall-e",
    "dall·e",
    "dalle",
    "comfyui",
    "automatic1111",
    "invoke ai",
    "invokeai",
    "novel ai",
    "novelai",
    "dreamstudio",
    "dream studio",
    "adobe firefly",
    "firefly",
    "leonardo ai",
    "leonardo.ai",
    "runway",
    "canva ai",
    "bing image creator",
    "ideogram",
    "nightcafe",
    "bluewillow",
    "getimg",
    "playground ai",
    "seaart",
    "tensor art",
]

# -----------------------------------------------------------------------
# Common AI filler / transition phrases
# -----------------------------------------------------------------------
_AI_FILLER_PHRASES = [
    r"\bin conclusion\b",
    r"\bit is worth noting\b",
    r"\bit is important to note\b",
    r"\bit is essential to\b",
    r"\bit should be noted\b",
    r"\bas (an|a) AI\b",
    r"\bI am an AI\b",
    r"\bI'm an AI\b",
    r"\bas mentioned (above|earlier|previously)\b",
    r"\bfurthermore\b",
    r"\bmoreover\b",
    r"\badditionally\b",
    r"\bin summary\b",
    r"\bto summarize\b",
    r"\bin (this|the) context\b",
    r"\bit is crucial\b",
    r"\bplays? a (crucial|vital|key|pivotal) role\b",
    r"\bultimately\b",
    r"\bdelve into\b",
    r"\bunlock(ing)? the (full )?potential\b",
    r"\bcomprehensive\b",
    r"\brobust\b",
    r"\bseamless(ly)?\b",
    r"\bleverage\b",
    r"\btailored\b",
    r"\bsignificant(ly)?\b",
]


class AIDetector:
    """
    Heuristic-based local detector for AI-generated content.
    Operates fully offline — no external API calls.
    """

    # ------------------------------------------------------------------
    # Text analysis
    # ------------------------------------------------------------------

    def analyze_text(self, text: str) -> dict:
        """
        Analyses text using local heuristics to estimate the likelihood
        that it was generated by an AI language model.

        Heuristics applied:
        1. Average sentence length (AI tends toward medium-long, uniform sentences)
        2. Type-Token Ratio (TTR) — vocabulary richness
        3. Repetition of n-grams
        4. Presence of common AI filler phrases

        Args:
            text: The text string to analyse.

        Returns:
            dict with:
                - 'score': float in [0.0, 1.0] (higher = more likely AI)
                - 'confidence': 'low' | 'medium' | 'high'
                - 'indicators': list of human-readable indicator strings
        """
        if not text or not text.strip():
            return {"score": 0.0, "confidence": "low", "indicators": ["Empty or blank input."]}

        indicators = []
        score = 0.0

        # --- Tokenise ---
        sentences = self._split_sentences(text)
        words = re.findall(r"\b[a-zA-Z']+\b", text.lower())

        # 1. Average sentence length
        if sentences:
            avg_len = sum(len(re.findall(r"\b\w+\b", s)) for s in sentences) / len(sentences)
            if 15 <= avg_len <= 35:
                score += 0.15
                indicators.append(
                    f"Average sentence length ({avg_len:.1f} words) falls in typical AI range (15–35)."
                )
            # Very uniform sentence lengths (low std-dev) → AI-like
            lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences if s.strip()]
            if len(lengths) > 2:
                mean_len = sum(lengths) / len(lengths)
                variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
                std_dev = math.sqrt(variance)
                cv = std_dev / mean_len if mean_len > 0 else 1.0  # coefficient of variation
                if cv < 0.25:
                    score += 0.15
                    indicators.append(
                        f"Sentence lengths are very uniform (CV={cv:.2f}), suggesting machine generation."
                    )

        # 2. Type-Token Ratio (TTR)
        if words:
            unique_words = set(words)
            ttr = len(unique_words) / len(words)
            # AI text often has moderate TTR (0.4–0.7); very low = repetitive, very high = rare
            if 0.35 <= ttr <= 0.70:
                score += 0.10
                indicators.append(f"Vocabulary richness (TTR={ttr:.2f}) is in the typical AI range.")
            elif ttr < 0.25:
                score += 0.20
                indicators.append(
                    f"Very low vocabulary richness (TTR={ttr:.2f}); high word repetition detected."
                )

        # 3. Bigram repetition
        if len(words) >= 4:
            bigrams = list(zip(words, words[1:]))
            unique_bigrams = set(bigrams)
            bigram_rep_ratio = 1.0 - len(unique_bigrams) / len(bigrams)
            if bigram_rep_ratio > 0.15:
                score += 0.15
                indicators.append(
                    f"High bigram repetition ratio ({bigram_rep_ratio:.2f}) suggests templated output."
                )

        # 4. AI filler phrases
        filler_hits = []
        for pattern in _AI_FILLER_PHRASES:
            if re.search(pattern, text, re.IGNORECASE):
                filler_hits.append(pattern.strip(r"\b"))
        if filler_hits:
            hit_score = min(len(filler_hits) * 0.08, 0.35)
            score += hit_score
            indicators.append(
                f"Found {len(filler_hits)} common AI filler phrase(s): "
                + ", ".join(f"'{p}'" for p in filler_hits[:5])
            )

        score = min(score, 1.0)

        if score >= 0.6:
            confidence = "high"
        elif score >= 0.3:
            confidence = "medium"
        else:
            confidence = "low"

        return {"score": round(score, 4), "confidence": confidence, "indicators": indicators}

    @staticmethod
    def _split_sentences(text: str) -> list:
        """Naive sentence splitter on '.', '!', '?' boundaries."""
        parts = re.split(r"(?<=[.!?])\s+", text.strip())
        return [p for p in parts if p.strip()]

    # ------------------------------------------------------------------
    # Image metadata analysis
    # ------------------------------------------------------------------

    def analyze_image_metadata(self, filepath: str) -> dict:
        """
        Checks image EXIF metadata for signs of AI generation.

        Indicators checked:
        - EXIF Software field matches known AI generator names
        - Presence of AI-related keywords in ImageDescription / UserComment
        - Absence of camera make/model (AI images lack hardware info)
        - Presence of art-style metadata without corresponding camera data

        Args:
            filepath: Path to an image file.

        Returns:
            dict with:
                - 'is_likely_ai': bool
                - 'evidence': list of evidence strings
                - 'software': software string or None
        """
        result = {"is_likely_ai": False, "evidence": [], "software": None}

        if not PILLOW_AVAILABLE:
            result["evidence"].append("Pillow not available; metadata check skipped.")
            return result

        if not os.path.isfile(filepath):
            result["evidence"].append("File not found.")
            return result

        try:
            img = Image.open(filepath)
            raw_exif = img._getexif()
        except Exception as exc:
            result["evidence"].append(f"Could not read EXIF: {exc}")
            return result

        if raw_exif is None:
            raw_exif = {}

        exif = {TAGS.get(tag, str(tag)): val for tag, val in raw_exif.items()}

        evidence = []
        is_ai = False

        # Check Software field
        software = exif.get("Software", "")
        if isinstance(software, bytes):
            software = software.decode("utf-8", errors="replace")
        software = (software or "").strip()
        result["software"] = software if software else None

        if software:
            sw_lower = software.lower()
            for sig in _AI_SOFTWARE_SIGNATURES:
                if sig in sw_lower:
                    evidence.append(f"Software field matches known AI generator: '{software}'")
                    is_ai = True
                    break

        # Check ImageDescription and UserComment for AI keywords
        for field in ("ImageDescription", "UserComment"):
            val = exif.get(field, "")
            if isinstance(val, bytes):
                val = val.decode("utf-8", errors="replace")
            if val:
                val_lower = val.lower()
                for sig in _AI_SOFTWARE_SIGNATURES:
                    if sig in val_lower:
                        evidence.append(
                            f"'{field}' contains AI generator reference: '{val[:120]}'"
                        )
                        is_ai = True
                        break

        # Check absence of camera hardware info
        has_make = bool(exif.get("Make"))
        has_model = bool(exif.get("Model"))
        has_focal = bool(exif.get("FocalLength"))
        has_iso = bool(exif.get("ISOSpeedRatings"))

        if not has_make and not has_model:
            evidence.append("No camera Make or Model found in EXIF — typical of AI-generated images.")
            # Only bump score, don't mark as AI on its own
            if not has_focal and not has_iso:
                evidence.append("No focal length or ISO data — further consistent with AI generation.")
                if not is_ai:
                    # Weak signal only if combined with software absence
                    pass  # Do not flip is_likely_ai on this alone

        result["is_likely_ai"] = is_ai
        result["evidence"] = evidence
        return result

    # ------------------------------------------------------------------
    # Combined file analysis
    # ------------------------------------------------------------------

    def analyze_file(self, filepath: str) -> dict:
        """
        Combines image metadata analysis with any available content analysis
        to produce a unified result dict.

        For text files (.txt, .md, .rst, .csv, .log), also runs analyze_text().
        For image files, runs analyze_image_metadata().

        Args:
            filepath: Path to the file to analyse.

        Returns:
            dict with:
                - 'filepath': str
                - 'file_type': 'image' | 'text' | 'unknown'
                - 'metadata_analysis': result of analyze_image_metadata (images only)
                - 'text_analysis': result of analyze_text (text files only)
                - 'is_likely_ai': bool (combined verdict)
                - 'summary': human-readable string
        """
        result = {
            "filepath": filepath,
            "file_type": "unknown",
            "metadata_analysis": None,
            "text_analysis": None,
            "is_likely_ai": False,
            "summary": "",
        }

        if not os.path.isfile(filepath):
            result["summary"] = "File not found."
            return result

        ext = os.path.splitext(filepath)[1].lower()

        _image_exts = {".jpg", ".jpeg", ".png", ".tiff", ".tif", ".bmp", ".webp", ".gif"}
        _text_exts = {".txt", ".md", ".rst", ".csv", ".log", ".py", ".js", ".html", ".xml"}

        if ext in _image_exts:
            result["file_type"] = "image"
            meta = self.analyze_image_metadata(filepath)
            result["metadata_analysis"] = meta
            result["is_likely_ai"] = meta.get("is_likely_ai", False)
            result["summary"] = (
                "Likely AI-generated image." if result["is_likely_ai"]
                else "No strong AI generation indicators found in image metadata."
            )

        elif ext in _text_exts:
            result["file_type"] = "text"
            try:
                with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
                    text = fh.read()
            except Exception as exc:
                result["summary"] = f"Could not read file: {exc}"
                return result
            text_result = self.analyze_text(text)
            result["text_analysis"] = text_result
            result["is_likely_ai"] = text_result.get("score", 0.0) >= 0.5
            result["summary"] = (
                f"Text AI score: {text_result['score']:.2f} "
                f"(confidence: {text_result['confidence']})"
            )

        else:
            result["summary"] = f"File type '{ext}' not supported for AI detection."

        return result
